name: Build and Push Docker Image
on:
    push:
        branches:
            - 'master'
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            target-os: [linux android]
            qt-version: [6.8]

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to DockerHub
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3.0.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5.3.0
          with:
            context: .
            file: ./${{ matrix.qt-version }}-${{ matrix.target-os }}.Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/docker-qt:${{ matrix.qt-version }}-${{ matrix.target-os }}-latest
              ${{ secrets.DOCKERHUB_USERNAME }}/docker-qt:${{ matrix.qt-version }}-${{ matrix.target-os }}
              ghcr.io/${{ github.actor }}/docker-qt:${{ matrix.qt-version }}-${{ matrix.target-os }}-latest
              ghcr.io/${{ github.actor }}/docker-qt:${{ matrix.qt-version }}-${{ matrix.target-os }}

            labels: ${{ steps.meta.outputs.labels }}
